#Название сайта с документацией по продукту "Робот и точка"
site_name: OnlyRobots Docs

#Структура сайта
nav:
  - Домашняя страница: index.md
  - Глоссарий: glossary.md
  - Концепция продукта: vision.md

#Тема для оформления сайта
theme: 
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  language: ru
  features:
    #- navigation.instant # Мгновенная загрузка
    - navigation.expand # Автоматическое открытие подразделов на панели слева
    #- navigation.path # Над заголовком каждой страницы отображается путь
    #- navigation.top # Кнопка «назад-вверх»
    #- navigation.footer # Переключение кнопками предыдущей/следующей страницы в футере
    #- navigation.tabs # Навигационные вкладки
    #- navigation.sections # Отображение верхних вкладок на панели слева
    - navigation.indexes # Скрыть дублирование заголовка на панели слева
    #- toc.integrate # Интеграция подразделов в панель слева
    #- toc.follow # Автоматическая прокрутка боковой панели при прокрутке
    #- search.highlight # Подсветка вхождений в тексте
    #- search.suggest # Автозавершение поискового запроса
    #- content.code.copy # Кнопка копирования кода